airtable integration
designunit/sisu pull request #12
Opened 2020-11-19 19:51 UTC by HappyCthulhu

2020-11-19 20:10 UTC, tmshv requested changes

2020-11-19 20:10 UTC, tmshv commented on get_airtable_data.py
> +    'Authorization': 'Bearer key0YA6rgADmbxx61',
ключи авторизации в гите хранить нельзя это зашквар
кстати, репозиторий открытый, так что он уже скомпрометирован

2020-11-19 20:10 UTC, tmshv commented on get_airtable_data.py
> +def hex_to_rgb(record_value, column_name):
сигнатура у такой функции должна быть `hex_to_rgb(color: str) -> Tuple[int, int, int]`

2020-11-19 20:10 UTC, tmshv commented on get_airtable_data.py
> +def check_field_is_not_empty(record_value, column_name):
по дзену делается так: `column_name in record_value`
т.е вся функция под такую задачу не нужна

2020-11-19 20:10 UTC, tmshv commented on get_airtable_data.py
> +    elif check_field_is_not_empty(record_value, 'pattern'):
тут есть повтор

2020-11-19 20:10 UTC, tmshv commented on get_airtable_data.py
> +print(f'ответ airtable: {table_json}')
нахер тут принт

2020-12-03 16:52 UTC, tmshv commented
```py
def update_airtable(airtable_token, airtable_id, airtable_name, column_name, cell_value):
    headers = {
        'Authorization': 'Bearer %s' % airtable_token,
        'Content-Type': 'application/json',
    }
    
    fields={}
    fields[column_name] = cell_value
    
    data = {
        "records": [
            {
                "id": "recbzCbB1csb82W4N",
                "fields": fields,
            }
        ]
    }
    response = requests.patch('https://api.airtable.com/v0/appwLoUM2FeZap2P4/Pitkyaranta_test', headers=headers, data=json.dumps(data))
    return response.json()
```

2020-12-04 12:59 UTC, tmshv requested changes

2020-12-04 12:59 UTC, tmshv commented on update_airtable_data.py
> +def update_airtable(airtable_token, airtable_id, airtable_name, line_id, column_name, cell_value):
```py
def update_airtable(token: str, base_id: str, table_name: str, patch: Dict):
    pass

patch = {
    'code': '<some_dc_code>',
    'solidColor': '#ffffff',
    'pattern': 'Grid',
}
```

2020-12-04 12:59 UTC, tmshv commented on update_airtable_data.py
> +    update_airtable(token, table_id, table_name, id, element['column'], element['change'])
```py
if __name__ == '__main__':
     pass
```

2020-12-04 13:41 UTC, tmshv requested changes

2020-12-04 13:41 UTC, tmshv commented on update_airtable_data.py
> +    patch_dict = [
`patches`

2020-12-04 14:57 UTC, tmshv requested changes

2020-12-04 14:57 UTC, tmshv commented on update_airtable_data.py
> +            "id": "%s" % row_dict['id'],
`'%s' % 'something' == 'something'`

2020-12-04 14:57 UTC, tmshv commented on update_airtable_data.py
> +        if value['fields']['code'] == '%s' % code:
what the fuck is `%`?

2020-12-04 14:57 UTC, tmshv commented on update_airtable_data.py
> +def render_patch_dict(data_dict, row_dict):
signature is `create_patch(row_id, patch)`

2020-12-04 14:57 UTC, tmshv commented on update_airtable_data.py
> +        data_dict = render_patch_dict(patch, element)
```py
row_id = get_row_id(table, partial['code'])
data = create_patch(row_id, partial)
```

2020-12-04 15:09 UTC, HappyCthulhu commented on update_airtable_data.py
> +        if value['fields']['code'] == '%s' % code:
vsmisle? tak je variavles v stroku v pitione vstavlyautsya (paste)

2020-12-04 15:11 UTC, HappyCthulhu commented on update_airtable_data.py
> +            "id": "%s" % row_dict['id'],
Почему идет операция сравнения, а не присваивания? Что мы проверяем?
И, если это ошибка, чем твой вариант отличается от моего?

2020-12-04 15:12 UTC, HappyCthulhu commented on update_airtable_data.py
> +def render_patch_dict(data_dict, row_dict):
1. Нужно передавать переменную id, а не значение словаря id, да?
2. Нужно изменить название функций

Так?

2020-12-04 15:20 UTC, HappyCthulhu commented on update_airtable_data.py
> +def render_patch_dict(data_dict, row_dict):
У нас есть изначальный список со структурой:
    data_list = [
        {
            'code': 'B_BKb',
            'color': 'цвет изменен',
            'pattern': 'хач 43671',
        },
        {
            'code': 'B_BKp',
            'color': 'цвет изменен еще раз',
            'pattern': 'хач 3',
        }

    ]

У нас есть patch, который имеет другую структуру. Почему ты против идеи добавить элемент data_list в функцию, которая добавит его в patch?

Потом я подумал, что ты хочешь весь цикл и всю сборку patch добавить внутрь функции create_patch. Но, типа, зачем тогда передавать row_id, если его придется внутри функции create_patch находить?

2020-12-05 08:55 UTC, tmshv requested changes

2020-12-05 08:55 UTC, tmshv commented on update_airtable_data.py
> +        if value['fields']['code'] == '%s' % code:
`code` is already string

2020-12-05 08:55 UTC, tmshv commented on update_airtable_data.py
> +def render_patch_dict(data_dict, row_dict):
plz use **markdown** *magic* to show
```
some code
```

2020-12-05 08:55 UTC, tmshv commented on update_airtable_data.py
> +            "id": "%s" % row_dict['id'],
just remove `%` shit

2020-12-05 09:22 UTC, tmshv reviewed
Замени в `update_airtable`

```
```

2020-12-05 09:23 UTC, tmshv requested changes
Замени в `update_airtable`

```
requests.patch('https://api.airtable.com/v0/%s/%s' % (airtable_id, airtable_name), headers=headers,
                               data=json.dumps(patch))
```
на просто `print(patch)`

и посмотри, почему работать не будет

2020-12-05 10:00 UTC, tmshv requested changes

2020-12-07 16:28 UTC, tmshv requested changes

2020-12-07 16:28 UTC, tmshv commented on rhinolib.py
> +        return None
верни как было в `get_sisufile`

2020-12-07 16:28 UTC, tmshv commented on SisuPull_cmd.py
> +        rs.LayerVisible(layer, visible=True)
это зачем? где запуск апдейта?

2020-12-07 16:28 UTC, tmshv commented on get_airtable_data.py
> +import json
зачем этот файл если есть `air table.py`?

2020-12-07 16:28 UTC, tmshv commented on rhinolib.py
> +    update_sisufile()
нинада

2020-12-07 16:28 UTC, tmshv commented on update_airtable.json
> +}
нинада

2020-12-07 16:28 UTC, tmshv commented on update_airtable_data.py
> +import json
зачем еще 3й файл для airtable?

2020-12-07 19:56 UTC, tmshv requested changes

2020-12-07 19:56 UTC, tmshv commented on SisuPull_cmd.py
> +        json.dumps(read_sisufile(config), indent=4)
да где апдейт блеять

2020-12-08 10:23 UTC, HappyCthulhu commented on SisuPull_cmd.py
> +        json.dumps(read_sisufile(config), indent=4)
сделал

2020-12-08 15:53 UTC, tmshv approved these changes

2020-12-08 15:54 UTC, merged