Make create_color func more resistant to non-digit characters
designunit/sisu pull request #34
Opened 2021-04-29 17:05 UTC by HappyCthulhu

Now if this func took non-digital symbols, it return [0, 0, 0] in all cases

2021-05-01 14:12 UTC, tmshv requested changes

2021-05-01 14:12 UTC, tmshv commented on tests/test_sisulib.py
> +        related_layers = get_related_layers(read_sisufile(PATH_TO_CONFIG_FILE))
test `read_sisufile` in separate test case.
put a constant here or open file directly

2021-05-03 16:34 UTC, HappyCthulhu commented on tests/test_sisulib.py
> +        related_layers = get_related_layers(read_sisufile(PATH_TO_CONFIG_FILE))
replaced with constant

2021-05-05 09:46 UTC, tmshv requested changes

2021-05-05 09:46 UTC, tmshv commented on requirements.txt
> +zipp==1.2.0
what the hell is this? just `pytest` isnt enough?

2021-05-05 09:46 UTC, tmshv commented on Dockerfile
> +
please

remove

this

empty

lines

but

keep

EOL

2021-05-05 09:46 UTC, tmshv commented on .dockerignore
> +# TODO: optimize this
what you wanted to optimize?

2021-05-05 09:46 UTC, tmshv commented on .dockerignore
> +__plugin__.py
we need this file inside a container

2021-05-05 13:28 UTC, HappyCthulhu commented on .dockerignore
> +# TODO: optimize this
maybe its possible to ingore __pycache__ with one, not two strings

2021-05-05 13:28 UTC, HappyCthulhu commented on requirements.txt
> +zipp==1.2.0
its pip freeze stuff

2021-05-05 13:32 UTC, tmshv commented on requirements.txt
> +zipp==1.2.0
almost all of them is transitive dependencies
add only direct ones

2021-05-05 13:33 UTC, tmshv commented on .dockerignore
> +# TODO: optimize this
yep just keep `__pycache__` line

2021-05-05 13:35 UTC, HappyCthulhu commented on requirements.txt
> +zipp==1.2.0
corrected

2021-05-05 13:35 UTC, HappyCthulhu commented on Dockerfile
> +
fixed

2021-05-05 13:35 UTC, HappyCthulhu commented on .dockerignore
> +__plugin__.py
fixed

2021-05-05 13:44 UTC, tmshv requested changes
and add a Test section to readme with docker commands

```
docker build -t designunit/sisu .
docker run --rm --name sisu designunit/sisu
```

2021-05-05 13:44 UTC, tmshv commented on tests/test_sisulib.py
> +PATH_TO_CONFIG_FILE = 'sisufile.json'
unused variable

2021-05-05 13:44 UTC, tmshv commented on tests/test_sisulib.py
> +            {u'layer': [u'Default', {u'color': [255, 0, 0], u'lineWeight': 1, u'lineType': u'continuous'}],
why `u''`?

2021-05-05 13:44 UTC, tmshv commented on tests/test_sisulib.py
> +        json = {u'version': u'0', u'data': [
variable is not a json
it is a config

2021-05-05 13:44 UTC, tmshv commented on tests/test_sisulib.py
> +                                                     u'layerSuffix': u'_HATCH'}]}]}
plz format this shit
i can't read it

2021-05-22 17:21 UTC, tmshv approved these changes

2021-05-22 17:21 UTC, merged