issue 42 fix
designunit/sisu pull request #43
Opened 2021-06-16 14:53 UTC by modernpacifist

2021-06-16 16:14 UTC, tmshv requested changes

2021-06-16 16:14 UTC, tmshv commented on sisulib.py
> +from rhinoscriptsyntax import DocumentPath
No `rhinoscriptsyntax` in this file. We were talking about it.

2021-06-16 18:20 UTC, tmshv requested changes

2021-06-16 18:20 UTC, tmshv commented on sisulib.py
> +    rhinofile_path = get_rhinofile_path()
You created transitive dependency of `rhinoscriptsyntax`. Nothing changed.

2021-06-16 19:11 UTC, modernpacifist commented on sisulib.py
> +    rhinofile_path = get_rhinofile_path()
Is there a way to get Rhino file without `rhinoscriptsyntax`?

2021-06-17 13:03 UTC, tmshv commented on sisulib.py
> +    rhinofile_path = get_rhinofile_path()
Pass it to hash function as argument. We were discussed about it.

2021-06-17 13:26 UTC, modernpacifist commented on sisulib.py
> +    rhinofile_path = get_rhinofile_path()
- get_hash() is a method in Sisuconfig classes
- takes kwargs as argument
- sorts them in order and returns md5 hash

2021-06-17 16:48 UTC, modernpacifist commented
The version of the script will be passed as a parameter or must be parsed from __plugin__.py?

2021-08-04 16:45 UTC, tmshv requested changes

2021-08-04 16:45 UTC, tmshv commented on sisulib.py
> +            sisufile_content = "".join(map(str, f.readlines()))
why not just `f.read()`?

2021-08-04 16:45 UTC, tmshv commented on sisulib.py
> +    def get_hash(self, **kwargs):
add tests

2021-08-06 17:13 UTC, tmshv requested changes

2021-08-06 17:13 UTC, tmshv commented on sisulib.py
> +        values_string = "".join(values)
make it more pythonic:

```py
values = "".join([
    str(v)
    for k, v in sorted(kwargs.items(), lambda k, v: k)
])
```

or:

```py
values = "".join([
    str(kwargs[key])
    for key in sorted(kwargs)
])
```

2021-08-06 17:54 UTC, tmshv approved these changes

2021-08-06 17:54 UTC, merged