Add/release pipeline
designunit/sisu pull request #51
Opened 2021-09-02 18:07 UTC by modernpacifist

2021-09-03 13:17 UTC, tmshv requested changes

2021-09-03 13:17 UTC, tmshv commented on .github/workflows/release-asset.yaml
> +        zip -r sisu_src.rhi . -i \*.py -x conftest.py tests/*
Call this file `SISU_XXXX.rhi` where `XXXX` is a version of release taken from `__plugin__.py` but without dots. Can you do it in bash?

2021-09-03 19:28 UTC, modernpacifist commented on .github/workflows/release-asset.yaml
> +        zip -r sisu_src.rhi . -i \*.py -x conftest.py tests/*
Yeah, no problem

2021-09-04 05:17 UTC, modernpacifist commented
Found a bug in this solution, do not merge

2021-09-07 17:35 UTC, tmshv submitted a review, later dismissed

2021-09-09 14:54 UTC, tmshv approved these changes

2021-09-09 14:54 UTC, merged