leaders
designunit/sisu pull request #62
Opened 2021-10-25 12:22 UTC by grigorybaluev

2021-11-02 15:13 UTC, grigorybaluev commented
Message: SisuConfig instance has no attribute 'get_block_by_id'

Traceback:
  line 84, in RunCommand, "\\unit4\unit4\#Uspace\GB\du4\sisu\sisu_leader_01.py"
  line 109, in <module>, "\\unit4\unit4\#Uspace\GB\du4\sisu\sisu_leader_01.py"

2021-11-10 15:05 UTC, grigorybaluev commented
SisuLeaders ready for refactoring by modernpacifist

2021-11-10 16:55 UTC, tmshv requested changes

2021-11-10 16:55 UTC, tmshv commented on SisuLeaders_cmd.py
> +    objects = rs.GetObjects('Select objects to add leaders', 0, True, True)
why this instead of one line with filter?

2021-11-10 16:55 UTC, tmshv commented on SisuLeaders_cmd.py
> +    pts_to_move = update_points_positions(pts, clusters, target_y_dist, target_xy_dist, leader_layer)
should return list of updated clusters, not just points

2021-11-10 16:55 UTC, tmshv commented on SisuLeaders_cmd.py
> +    for leader_cluster, text_pt_moved in zip(clusters, pts_to_move):
so this `zip` it not needed

2021-11-10 16:55 UTC, tmshv commented on SisuLeaders_cmd.py
> +    leaders_fin = []
rm this

2021-11-10 16:55 UTC, tmshv commented on SisuLeaders_cmd.py
> +            rs.ObjectLayer(leader, leader_layer)
move this to `create_multileader` function

2021-11-10 16:55 UTC, tmshv commented on SisuLeaders_cmd.py
> +    pts = [i['leader_text_pt'] for i in clusters]
move this to `update_points_positions`

2021-11-10 16:55 UTC, tmshv commented on SisuLeaders_cmd.py
> +            continue
delete

2021-11-11 09:37 UTC, tmshv requested changes

2021-11-11 09:37 UTC, tmshv commented on SisuLeaders_cmd.py
> +            clusters.append(cluster)
better to drop this `if`
`for` on empty list will do 0 iters

2021-11-11 09:37 UTC, tmshv commented on SisuLeaders_cmd.py
> +            hatches.append(object)
run `rs.ObjectType` once per iter

2021-11-11 09:37 UTC, tmshv commented on SisuLeaders_cmd.py
> +    objects = rs.GetObjects('Select objects to add leaders', 4 | 4096 | 65536, True, True)
this strange number literals is called *magic numbers*
use variables instead of literals
define them at the top of this file
like that:
```py
OBJECT_TYPE_INSTANCE = 4096
```

2021-11-18 21:58 UTC, tmshv approved these changes

2021-11-18 21:58 UTC, merged